on:
  workflow_dispatch

name: Ethan Test

jobs:
  EthanFirstJob:
    runs-on: ubuntu-latest
    container: osgeo/gdal:ubuntu-small-latest
    steps: 
    - name: Initialize Environment
      run: |
           apt-get update
           apt-get install -y python3-pip
           pip3 install geopandas

    - name: Download Repo
      uses: actions/checkout@v2.3.2

    - name: Example Script
      run: |
           ls
           ShapeFileChecks.py         